import { Material, FixedCost, Budget, CatalogMaterial } from './types';

export const MOCK_MATERIALS: CatalogMaterial[] = [
  {
    id: '1',
    name: 'MDF Branco 18mm',
    category: 'Chapas',
    price: 245.00,
    unit: 'Chapa',
    qty: 1,
    thickness: '18mm',
    image: 'https://picsum.photos/seed/wood1/400/400',
    trending: true,
  },
  {
    id: '2',
    name: 'MDF Louro Freijó 15mm',
    category: 'Chapas',
    price: 312.00,
    unit: 'Chapa',
    qty: 1,
    thickness: '15mm',
    image: 'https://picsum.photos/seed/wood2/400/400',
  },
  {
    id: '3',
    name: 'Dobradiça Amortecida 35mm',
    category: 'Dobradiças',
    price: 18.90,
    unit: 'Unid',
    qty: 1,
    thickness: '35mm',
    image: 'https://picsum.photos/seed/hinge/400/400',
    trending: true,
  },
  {
    id: '4',
    name: 'Corrediça Telescópica 450mm',
    category: 'Corrediças',
    price: 32.50,
    unit: 'Par',
    qty: 1,
    thickness: '450mm',
    image: 'https://picsum.photos/seed/slide/400/400',
  },
  {
    id: '5',
    name: 'Puxador Alça Alumínio 160mm',
    category: 'Puxadores',
    price: 24.00,
    unit: 'Unid',
    qty: 1,
    thickness: '160mm',
    image: 'https://picsum.photos/seed/handle/400/400',
  },
  {
    id: '6',
    name: 'Fita de Borda PVC Branco 22mm',
    category: 'Fita de Bordas',
    price: 45.00,
    unit: 'Rolo 20m',
    qty: 1,
    thickness: '22mm',
    image: 'https://picsum.photos/seed/edge/400/400',
  },
  {
    id: '7',
    name: 'Parafuso 4x40mm (Cento)',
    category: 'Ferragens',
    price: 15.00,
    unit: 'Cento',
    qty: 1,
    thickness: '4x40mm',
    image: 'https://picsum.photos/seed/screw/400/400',
  },
  {
    id: '8',
    name: 'Suporte Prateleira Invisível',
    category: 'Acessórios',
    price: 12.50,
    unit: 'Unid',
    qty: 1,
    thickness: '-',
    image: 'https://picsum.photos/seed/shelf/400/400',
  },
  {
    id: '9',
    name: 'MDF Grafite 18mm',
    category: 'Chapas',
    price: 285.00,
    unit: 'Chapa',
    qty: 1,
    thickness: '18mm',
    image: 'https://picsum.photos/seed/wood3/400/400',
  },
  {
    id: '10',
    name: 'Dobradiça Reta Standard',
    category: 'Dobradiças',
    price: 8.50,
    unit: 'Unid',
    qty: 1,
    image: 'https://picsum.photos/seed/hinge2/400/400',
  },
];

export const MOCK_FIXED_COSTS: { operacional: FixedCost[], pessoal: FixedCost[] } = {
  operacional: [
    { id: '1', name: 'Aluguel Barracão', description: 'Manutenção & Infraestrutura', value: 1100.00 },
    { id: '2', name: 'Água', description: 'Consumo Variável Fixo', value: 40.00 },
    { id: '3', name: 'Luz', description: 'Energia Trifásica Workshop', value: 60.00 },
    { id: '4', name: 'Internet', description: 'Link Dedicado Fibra', value: 100.00 },
  ],
  pessoal: [
    { id: '5', name: 'Prolabore', description: 'Remuneração Sócios', value: 1500.00 },
    { id: '6', name: 'Salários de Produção', description: 'Encargos Inclusos (2 colaboradores)', value: 890.00 },
  ],
};

export const MOCK_BUDGET: Budget = {
  id: 'ORD-2023-0892',
  title: 'Armário Suíte Master',
  ref: '#ORD-2023-0892',
  clientName: 'João Silva',
  clientPhone: '(11) 98765-4321',
  clientAddress: 'Rua das Flores, 123 - São Paulo',
  environment: 'Suíte Master',
  materials: [
    { description: 'Chapa MDF Branco 15mm', spec: '2750 × 1840mm', qty: 3, unitPrice: 280.00 },
    { description: 'Fita de Borda PVC', spec: 'Rolo 20m - Branco', qty: 2, unitPrice: 45.00 },
    { description: 'Cola de Contato', spec: 'Lata 2.8kg', qty: 1, unitPrice: 115.00 },
    { description: 'Ferragens (Corrediças)', spec: 'Telescópica 450mm', qty: 4, unitPrice: 32.50 },
  ],
  labor: [
    { role: 'Projetista', description: 'Desenvolvimento técnico', value: 180.00 },
    { role: 'Marceneiro', description: 'Produção e Montagem', value: 450.00 },
  ],
  margin: 0.60,
  taxes: 0,
  status: 'draft',
  date: '2023-10-25',
};
